language: node_js
addons:
  apt:
    packages:
      - iproute2
sudo: required
dist: trusty
services:
  - docker
 
before_install:
- docker pull backstopjs/backstopjs:3.8.5

node_js:
- 8.5

install:
- npm install

script:
- gulp test:generateCIConfig
- gulp test:visual

branches:
  only:
  - develop
